version: 2

project_name: e2e-tests

builds:
  - skip: true

release:
  disable: true

dockers_v2:
  - images:
      - "ghcr.io/clementnuss/e2e-tests"
    tags:
      - "{{ .Version }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64
    dockerfile: Dockerfile
    extra_files:
      - bin/
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "E2E tests for Kubernetes cluster"
      "org.opencontainers.image.url": "https://github.com/clementnuss/e2e-tests"
      "org.opencontainers.image.source": "https://github.com/clementnuss/e2e-tests"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
