apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - rbac.yaml
  - cronjob.yaml

commonLabels:
  app.kubernetes.io/name: e2e-tests
  app.kubernetes.io/component: testing
  app.kubernetes.io/part-of: monitoring

images:
  - name: ghcr.io/clementnuss/e2e-tests
    newTag: latest
